### ISSUE TITLE
When creating a new page whose model uses [WithEditableChild], a nameless page sometimes is added

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#695]
We have a couple of page types whose models have [WithEditableChild] attributes and required details on them. Sometimes a weird thing happens when we add a new page of that type: along with the page we intended to create, sometimes an extra "phantom" page of the same type also gets created. The phantom page has no name, no content and is usually published. Any idea what could cause that to happen? I think this cropped up after we upgraded to version 2.9.2 or 2.9.3 (we are currently on the latter).

Unfortunately for debugging purposes, this bug only occurs intermittently, and I haven't been able to pin down a reliable set of steps to reproduce the bug. With some of our models all we have to do is populate all of the free text details and save and publish for a phantom page to appear. For others I've found the phantom pages are more likely to appear if I trigger some sort of validation error (e.g.: omit a required detail), make some changes without fixing the error, unsuccessfully try to save and publish again, fix the error, and then save and publish. But all of the known affected models follow the same [WithEditableChild]/[EditableChildren] pattern I described in #689.

**Comment by ahmadh21** [comment]
Hello,
I am working on the project with laurachan and a couple of other developers. First of all, I want to say thank you for all the great work on N2. It has come a long way since we initially looked at it, and it continues to get better with every update.

To comment on the issue laura is reporting, it appears there are multiple things happening that may not all be related:
 1. a (no name) part appears in the listing of pages when saving/publishing, but disappears on refresh
 2. a (no name) page appears in the listing of pages when saving/publishing, that does not disappear on refresh
 3. a duplicate page of the one just created appears when saving/publishing, and does not disappear on refresh.

More details below:
1.
The least serious issue because the "phantom" items disappear from the list upon refresh. I have noticed it is triggered only when the parent node has a "WithEditableChild", with some data in the witheditablechild detail, and you attempt to edit/add a new page under that parent node. Immediately after saving the changes, this (no name) part appears in the listing, then goes away upon refreshing. See screenshot at the bottom.

2.
We haven't been able to reliably reproduce this. My suspicion is it revolves around an exception happening in the library that triggers this (no name) page to be created. I did witness it (but was not able to reproduce) when editing a page, not sure if it happens after creating a page. As Laura mentioned, it feels like this was introduced sometime in version 2.9.x.

3.
This is a strange one that seems to happen only when creating a new page. I was able to reproduce it a few times, but not reliably. Here is what I did just before it happened:
 1. Set up a blank project, with a root fallback node and our own custom startpage as the second node
 2. updated site settings, missed a few required fields, filled them in
 3. created a new template based on the dinamico mvc contentpage index.cshtml template, and did not change anything except the file name (CustomTemplate), and the re.definition.title ("Test Page A").
 4. Created a container page under the start page
 5. Created a page using the CustomTemplate I created, filled in title and text
As soon as I hit save and publish:
 - a new, published, page under the container was created with the name I specified
 - another page, unpublished and under the same container, was created with the same name, but with a ContentPage type (and not CustomTemplate type).

No matter what I tried, I could not reproduce this in that same manner or another manner. However, I did notice that when it did happen I was in debug mode, and various exceptions were being thrown and caught internally by the N2 library, but I never tracked down what they were, simply skipped over them in visual studio. Thinking about it now, it probably would have helped if I had captured them.

We will keep this thread updated with more details as we find them.

Screenshot for issue 1:
![n2cms_fakepart](https://cloud.githubusercontent.com/assets/4106366/11517778/b1937ddc-9840-11e5-8e26-a37f26f3a7d5.png)

Screenshot for issues 2 & 3 (an extreme example where both scenarios occurred):
![duplicatepages](https://cloud.githubusercontent.com/assets/4106366/11518538/1fe3e05a-9847-11e5-8b76-fad7bd5fd70a.JPG)

We're using the following n2cms packages (not including non-n2cms packages):
  <package id="N2CMS.Config" version="2.6.2" targetFramework="net452" />
  <package id="N2CMS.Config.SQLite" version="2.9.5" targetFramework="net452" />
  <package id="N2CMS.Dinamico" version="2.9.5" targetFramework="net452" />
  <package id="N2CMS.Library" version="2.9.5" targetFramework="net452" />
  <package id="N2CMS.Management" version="2.9.5" targetFramework="net452" />
  <package id="N2CMS.Mvc" version="2.9.5" targetFramework="net452" />
  <package id="N2CMS.Razor" version="2.9.5" targetFramework="net452" />
  <package id="N2CMS.ReusableParts" version="2.9.5" targetFramework="net452" />
  <package id="N2CMS.Search.Lucene" version="2.9.5" targetFramework="net452" />

**Comment by libardo** [comment]
Clearly the auto-save feature is causing some unintended side-effects. I'll try these steps to reproduce and try figure out what's going on

**Comment by libardo** [comment]
Sorry couldn't reproduce.

If you can reproduce this again look out for an ajax request to ...Content.ashx/autosave... This should return an id which is then passed along in the form post when saving and publishing.

**Comment by ahmadh21** [comment]
That sounds like a good lead. Will keep an eye out and report my findings.

On another note, I just realized it is the autosave on a page that uses witheditablechild causing the TransientObjectException. Here is what I did to reproduce every time:
 1. Edited a saved page with an witheditablechild detail (if you want sample code I can provide)
 2. Clicked around the edit screen, made some changes, until a POST to this url was made
```
Content.ashx/autosave?selected=/start-page/super-duper/a/test1234-sadf/&n2item=26&view=draft
```
 3. Clicked "save and publish" and received the yellow page error
This appears to be similar to #342 and possibly #353 and #689. If you would like I can report this as a separate issue. Is there a way to disable autosaving?

**Comment by ahmadh21** [comment]
I think we have a possible scenario. A duplicate page can be created when creating a new page if "Save and published" is clicked exactly the same time the very first autosave post happens. A possible solution could be to disable the saving button when an autosave post is triggered.
