### ISSUE TITLE
Show more than 100 sub pages..

### ISSUE THREAD

**Issue by freke1981SWE** [n2cms/n2cms#780]
We have a problem when more than 100 sub pages should be listed in the tree view in N2 admin.

The first 100 shows up, and after them Load remaining show up. This works fine the first time. But after the 100 + 100 is loaded the Load remaning don´t show up any more. And we have right now 206 sub pages. I´ve tracked the code and found in ContentHandler:

`private IEnumerable<Node<TreeNode>> GetChildren(HttpContextBase context)`
 
And it seems the limit is set by this code (in SyncChildCollectionStateAttribute.cs):
 static SyncChildCollectionStateAttribute()
        {
            LargeCollecetionThreshold = 100;
        }

Is there a way to override this value without needing to rebuild the N2 solution? (We use the nuget version right now.)

**Comment by bherila** [comment]
Probably need to add a config element for it, unfortunately. I am going to go ahead and merge this PR https://github.com/n2cms/n2cms/pull/779 so that you can see how to do it. Could you kindly help out by sending a PR for the corresponding configuration element, @freke1981SWE ?

Also @libardo in case he wants to chime in.

**Comment by bherila** [comment]
I updated the limit to 1,000 which is more than anyone has requested so far, and should be still doable in modern browsers.
